Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_Autobotline\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_Autobotline\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_Autobotline\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_PAIN168\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_PAIN168\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_PAIN168\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_bluewin888e\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_bluewin888e\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_bluewin888e\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_PAIN168v1\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_PAIN168v1\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_PAIN168v1\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_goatsportpuls\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_goatsportpuls\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_goatsportpuls\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_uefabet\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_uefabet\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_uefabet\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_Wingclub168v1\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_Wingclub168v1\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_Wingclub168v1\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message