@echo off
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_Xbotline\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_spinix282\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_789AI\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_789POWER\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_8bignew\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_chokdee55\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_kitti999\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_G669\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_EROS\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_UFAAXA\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_Legacybet88\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_PGWIN365\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_Itausa\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_CHILI9\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_catbet\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_luckygold22\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_dmpire24\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_SUPERMAX66\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_starroyal999\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_SEXYTH\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_POK49v1\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_lavagame\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_wingclub168\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_gootime789\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_top1omg\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_LIONS888\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_max1club\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_Vinngaming\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_RO998\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_WINHEROv1\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_plays2wins\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_Neganz\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_WINHEROv2\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_WINHEROv3\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_BESARKING\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_WINHEROv5\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_THEPRO88\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_EVSLOTS\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_UFA339\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_PGGAME\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_WINHEROv6\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_Winherov7\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_ak95\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_la95\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_Netflix555\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_Bahthai168\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_Tulip789\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_MARWINBET\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_RFX\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_MRK168\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_EURO1688\flex_message /Y
copy FOOTBALL.json C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message /Y

copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_Xbotline\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_spinix282\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_789AI\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_789POWER\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_8bignew\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_chokdee55\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_kitti999\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_G669\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_EROS\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_UFAAXA\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_Legacybet88\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_PGWIN365\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_Itausa\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_CHILI9\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_catbet\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_luckygold22\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_dmpire24\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_SUPERMAX66\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_starroyal999\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_SEXYTH\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_POK49v1\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_lavagame\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_wingclub168\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_gootime789\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_top1omg\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_LIONS888\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_max1club\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_Vinngaming\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_RO998\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_WINHEROv1\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_plays2wins\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_Neganz\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_WINHEROv2\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_WINHEROv3\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_BESARKING\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_WINHEROv5\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_THEPRO88\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_EVSLOTS\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_UFA339\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_PGGAME\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_WINHEROv6\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_Winherov7\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_ak95\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_la95\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_Netflix555\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_Bahthai168\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_Tulip789\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_MARWINBET\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_RFX\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_MRK168\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_EURO1688\flex_message /Y
copy "วิเคราะห์บอลสด.json" C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message /Y
timeout 3
