Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_Legacybet88\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_Itausa\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_catbet\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_SEXYTH\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_POK49v1\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_top1omg\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_LIONS888\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_max1club\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_plays2wins\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_PGGAME\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_ak95\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_la95\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_Bahthai168\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_Tulip789\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_lottoplus\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_EURO1688\flex_message
Copy-Item -Path "หวยลาว.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message

Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_Legacybet88\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_Itausa\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_catbet\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_SEXYTH\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_POK49v1\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_top1omg\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_LIONS888\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_max1club\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_plays2wins\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_PGGAME\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_ak95\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_la95\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_Bahthai168\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_Tulip789\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_lottoplus\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_EURO1688\flex_message
Copy-Item -Path "หวยรัฐบาล.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message

Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_Legacybet88\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_Itausa\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_catbet\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_SEXYTH\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_POK49v1\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_top1omg\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_LIONS888\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_max1club\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_plays2wins\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_PGGAME\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_ak95\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_la95\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_Bahthai168\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_Tulip789\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_lottoplus\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_EURO1688\flex_message
Copy-Item -Path "หวยฮานอย.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message

Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_Legacybet88\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_Itausa\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_catbet\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_SEXYTH\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_POK49v1\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_top1omg\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_LIONS888\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_max1club\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_plays2wins\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_PGGAME\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_ak95\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_la95\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_Bahthai168\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_Tulip789\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_lottoplus\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_EURO1688\flex_message
Copy-Item -Path "หวยหุ้น.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message

Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Legacybet88\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Itausa\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_catbet\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_SEXYTH\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_POK49v1\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_top1omg\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LIONS888\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_max1club\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_plays2wins\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_PGGAME\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_ak95\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_la95\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Bahthai168\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Tulip789\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_lottoplus\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_EURO1688\flex_message
Copy-Item -Path "GSBLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message

Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Legacybet88\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Itausa\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_catbet\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_SEXYTH\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_POK49v1\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_top1omg\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LIONS888\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_max1club\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_plays2wins\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_PGGAME\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_ak95\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_la95\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Bahthai168\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Tulip789\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_lottoplus\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_EURO1688\flex_message
Copy-Item -Path "HANOILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message

Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Legacybet88\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Itausa\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_catbet\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_SEXYTH\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_POK49v1\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_top1omg\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LIONS888\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_max1club\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_plays2wins\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_PGGAME\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_ak95\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_la95\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Bahthai168\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Tulip789\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_lottoplus\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_EURO1688\flex_message
Copy-Item -Path "HANOINORMALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message

Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Legacybet88\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Itausa\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_catbet\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_SEXYTH\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_POK49v1\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_top1omg\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LIONS888\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_max1club\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_plays2wins\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_PGGAME\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_ak95\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_la95\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Bahthai168\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Tulip789\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_lottoplus\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_EURO1688\flex_message
Copy-Item -Path "HANOISPECIALLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message

Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Legacybet88\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Itausa\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_catbet\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_SEXYTH\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_POK49v1\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_top1omg\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LIONS888\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_max1club\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_plays2wins\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_PGGAME\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_ak95\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_la95\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Bahthai168\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Tulip789\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_lottoplus\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_EURO1688\flex_message
Copy-Item -Path "HANOIVIPLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message

Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Legacybet88\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Itausa\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_catbet\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_SEXYTH\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_POK49v1\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_top1omg\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LIONS888\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_max1club\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_plays2wins\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_PGGAME\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_ak95\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_la95\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Bahthai168\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Tulip789\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_lottoplus\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_EURO1688\flex_message
Copy-Item -Path "LAOLOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message

Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Legacybet88\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Itausa\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_catbet\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_SEXYTH\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_POK49v1\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_top1omg\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LIONS888\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_max1club\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_plays2wins\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_PGGAME\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_ak95\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_la95\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Bahthai168\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Tulip789\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_lottoplus\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_EURO1688\flex_message
Copy-Item -Path "THAILOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message

Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Xbotline\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_kitti999\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_FINFINBLOX\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_BRAVO24H\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_CODHENG\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_UFAAXA\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Legacybet88\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Itausa\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_catbet\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_SEXYTH\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_POK49v1\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_wingclub168\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_top1omg\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LIONS888\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_MAX1OMG\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_max1club\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_allslotasiav1\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_plays2wins\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_WYNNMACAU\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_PGGAME\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_LKLUCKY168\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_ak95\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_la95\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Bahthai168\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_Tulip789\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_lottoplus\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY88\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_EURO1688\flex_message
Copy-Item -Path "YEEKEELOTTOS.json" -Destination C:\Users\Administrator\Desktop\API_QUEENPLAY\flex_message
